-- Insert sample pets
INSERT INTO public.pets (id, name, species, breed, age, gender, size, color, description, personality, health_status, vaccination_status, spayed_neutered, good_with_kids, good_with_pets, energy_level, image_url, status, arrival_date) VALUES
(
  'e4f7c8a1-2b3d-4e5f-9a6b-1c2d3e4f5a6b',
  'Max',
  'dog',
  'Golden Retriever',
  3,
  'male',
  'large',
  'golden',
  'Max is a friendly and energetic Golden Retriever who loves to play fetch and go for long walks. He''s great with children and other dogs. Max is fully trained and knows basic commands. He would be perfect for an active family with a yard.',
  ARRAY['friendly', 'energetic', 'playful', 'obedient'],
  'excellent',
  'up-to-date',
  true,
  true,
  true,
  'high',
  'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=800&h=600&fit=crop',
  'available',
  '2024-11-01'
),
(
  'a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
  'Luna',
  'cat',
  'Siamese',
  2,
  'female',
  'small',
  'cream and brown',
  'Luna is a beautiful Siamese cat with striking blue eyes. She''s playful, curious, and loves attention. Luna enjoys interactive toys and sunny windowsills. She would do well in a quiet home as the only pet.',
  ARRAY['playful', 'curious', 'affectionate', 'intelligent'],
  'excellent',
  'up-to-date',
  true,
  false,
  false,
  'medium',
  'https://images.unsplash.com/photo-1573865526739-10c1deaeac5e?w=800&h=600&fit=crop',
  'available',
  '2024-10-15'
),
(
  'b2c3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e',
  'Charlie',
  'dog',
  'Labrador Mix',
  1,
  'male',
  'medium',
  'black',
  'Charlie is a young, energetic pup full of life! He''s still learning but is very food-motivated and eager to please. Perfect for someone who wants to train a puppy. Great with kids and very social.',
  ARRAY['energetic', 'playful', 'social', 'eager to please'],
  'excellent',
  'up-to-date',
  false,
  true,
  true,
  'very high',
  'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&h=600&fit=crop',
  'available',
  '2024-11-10'
),
(
  'c3d4e5f6-7a8b-9c0d-1e2f-3a4b5c6d7e8f',
  'Bella',
  'cat',
  'Persian',
  4,
  'female',
  'medium',
  'white',
  'Bella is a gentle and calm Persian cat who loves to cuddle. She has a luxurious coat that requires regular grooming. Bella prefers a peaceful environment and would be ideal for seniors or quiet households.',
  ARRAY['gentle', 'calm', 'affectionate', 'quiet'],
  'excellent',
  'up-to-date',
  true,
  true,
  false,
  'low',
  'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=800&h=600&fit=crop',
  'available',
  '2024-09-20'
),
(
  'd4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f9a',
  'Rocky',
  'dog',
  'German Shepherd',
  5,
  'male',
  'large',
  'black and tan',
  'Rocky is a loyal and protective German Shepherd. He''s well-trained and obedient, making him an excellent companion for an experienced dog owner. Rocky needs regular exercise and mental stimulation.',
  ARRAY['loyal', 'protective', 'intelligent', 'obedient'],
  'excellent',
  'up-to-date',
  true,
  false,
  true,
  'high',
  'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=600&fit=crop',
  'available',
  '2024-08-05'
),
(
  'e5f6a7b8-9c0d-1e2f-3a4b-5c6d7e8f9a0b',
  'Milo',
  'cat',
  'Maine Coon',
  3,
  'male',
  'large',
  'tabby',
  'Milo is a majestic Maine Coon with a gentle giant personality. Despite his size, he''s incredibly gentle and affectionate. Milo gets along well with other pets and children. He loves to play and explore.',
  ARRAY['gentle', 'affectionate', 'playful', 'social'],
  'excellent',
  'up-to-date',
  true,
  true,
  true,
  'medium',
  'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=800&h=600&fit=crop',
  'available',
  '2024-10-01'
),
(
  'f6a7b8c9-0d1e-2f3a-4b5c-6d7e8f9a0b1c',
  'Daisy',
  'rabbit',
  'Holland Lop',
  1,
  'female',
  'small',
  'brown and white',
  'Daisy is an adorable Holland Lop rabbit with floppy ears and a sweet temperament. She''s litter-trained and loves fresh vegetables. Daisy enjoys gentle handling and would be perfect for a family with older children.',
  ARRAY['sweet', 'gentle', 'quiet', 'friendly'],
  'excellent',
  'up-to-date',
  true,
  true,
  true,
  'low',
  'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=800&h=600&fit=crop',
  'available',
  '2024-11-05'
),
(
  'a7b8c9d0-1e2f-3a4b-5c6d-7e8f9a0b1c2d',
  'Cooper',
  'dog',
  'Beagle',
  2,
  'male',
  'medium',
  'tricolor',
  'Cooper is a friendly Beagle with a great nose for adventure! He''s curious and loves to explore. Cooper is good with other dogs and children. He would thrive in a home with a secure backyard.',
  ARRAY['friendly', 'curious', 'playful', 'adventurous'],
  'excellent',
  'up-to-date',
  true,
  true,
  true,
  'medium',
  'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=800&h=600&fit=crop',
  'available',
  '2024-10-20'
);
